# clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: promotionplans-manager-binding
subjects:
- kind: ServiceAccount
  name: ed210
  namespace: ed210
roleRef:
  kind: ClusterRole
  name: promotionplans-manager
  apiGroup: rbac.authorization.k8s.io