apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: promotionplans-manager-binding
  namespace: ed210
subjects:
- kind: ServiceAccount
  name: ed210
  namespace: ed210
roleRef:
  kind: Role
  name: promotionplans-manager
  apiGroup: rbac.authorization.k8s.io