яірapiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: egc
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: eg
spec:
  gatewayClassName: eg
  listeners:
    - name: http
      protocol: HTTP
      port: 8080
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: egr
spec:
  hostnames:
  - demo.example.com
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: eg
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: test-1-service
      port: 8080
      weight: 1
    - group: ""
      kind: Service
      name: test-2-service
      port: 8080
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
