apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: environments.apps.gfk.com
spec:
  group: apps.gfk.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                cluster:
                  type: object
                  properties:
                    name:
                      type: string
                    projectID:
                      type: string
                    zone:
                      type: string
                    namespace:
                      type: string
                provider:
                  type: string
                  enum: ["gcp", "aws", "azure"]
                  required: ["name", "projectID", "zone", "namespace", "provider"]
                registry:
                  type: object
                  properties:
                    url:
                      type: string
                    prefix:
                      type: string
                  required: ["url"]
  scope: Namespaced
  names:
    plural: environments
    singular: environment
    kind: Environment
    shortNames: ["env"]