apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: notifications.apps.gfk.com
spec:
  group: apps.gfk.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
                description:
                  type: string
                enabled:
                  type: boolean
                type:
                  type: string
                  enum: ["slack", "teams", "discord"]
              required: ["url", "type"]
  scope: Namespaced
  names:
    plural: notifications
    singular: notification
    kind: Notification
    shortNames: ["notif"]
