apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: promotionflows.apps.gfk.com
spec:
  group: apps.gfk.com
  names:
    kind: PromotionFlow
    listKind: PromotionFlowList
    plural: promotionflows
    singular: promotionflow
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: ["flowMap"]
              properties:
                flowMap:
                  type: object
                  additionalProperties:
                    type: string