apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: rbac.apps.gfk.com
spec:
  group: apps.gfk.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                roles:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      allowedCommands:
                        type: array
                        items:
                          type: string
                      readOnly:
                        type: boolean
                tokens:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      token:
                        type: string
                contexts:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      token:
                        type: string
                      role:
                        type: string
  scope: Namespaced
  names:
    plural: rbac
    singular: rbac
    kind: RBAC
    shortNames: ["rbac"]
