apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
  name: kube-app-manager-metrics-service
  namespace: application-system
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
    controller-tools.k8s.io: "1.0"
  name: kube-app-manager-service
  namespace: application-system
spec:
  ports:
  - port: 443
  selector:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
    controller-tools.k8s.io: "1.0"