apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
  name: kube-app-manager-leader-election-role
  namespace: application-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
  name: kube-app-manager-kube-app-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.k8s.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.k8s.io
  resources:
  - applications/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
  name: kube-app-manager-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
  name: kube-app-manager-leader-election-rolebinding
  namespace: application-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-app-manager-leader-election-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: application-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
  name: kube-app-manager-kube-app-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-app-manager-kube-app-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: application-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: kube-app-manager
    control-plane: kube-app-manager
  name: kube-app-manager-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-app-manager-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: application-system